---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# OncReg

<!-- badges: start -->
<!-- badges: end -->

Tools for working with cancer registry data.
    
## Installation
 
You can install the development version of OncReg from [GitHub](https://github.com/hongconsulting/OncReg) with:

```r
remotes::install_github("hongconsulting/OncReg")
```

### Example: comma-separated free text
```{r example_delim}
library(OncReg)
treatment <- c("capecitabine",
               "LETROZOLE",
               "letrozole, palbociclib",
               "Letrozole,Ribociclib",
               "anastrozole, ribociclib")
treatment <- OR.delim.replace(treatment, "anastrozole", "ai")
treatment <- OR.delim.replace(treatment, "letrozole", "ai")
treatment <- OR.delim.replace(treatment, "palbociclib", "cdk46i")
treatment <- OR.delim.replace(treatment, "ribociclib", "cdk46i")
print(treatment)
```

### Example: immortal time bias
```{r example_tdc}
library(OncReg)
library(survival)
set.seed(24601)
n <- 500
data <- data.frame("id" = 1:n)
data$date.event <- rexp(n, rate = log(2)/6)
data$date.censor <- rexp(n, rate = log(2)/12)
data$time <- pmin(data$date.event, data$date.censor)
data$status <- as.numeric(data$date.event <= data$date.censor)

# patients undergo cycle 1 of placebo treatment at 1 month
data$date.cycle1 <- 1
data$date.cycle1[runif(n) < 0.05] <- NA
data$date.cycle1[data$date.cycle1 > data$time] <- NA
data$binary.cycle1 <- as.numeric(!is.na(data$date.cycle1))

# cycle 1 of placebo treatment as a binary indicator appears effective due to immortal time bias
coxph(Surv(data$time, data$status) ~ data$binary.cycle1)

# cycle 1 of placebo treatment as a time-dependent covariate recovers the null effect
OR.tdCox(data$id, data$time, data$status, X.tdc = data.frame("cycle1" = data$date.cycle1))
```

### Example: Microsoft Excel dates and survival analysis
```{r example_date}
library(OncReg)
data0 <- data.frame("id" = 1:5, 
                    "diagnosis" = c("01/01/00", "01/01/2000", "36526", "36526",
                                    "36526"), 
                    "progression" = c("01/01/2001", ".", "01/01/2001", "", NA), 
                    "review1" = c("01/07/2001", "01/07/2001", "01/07/2001", 
                                  "01/07/2001", "01/07/2001"), 
                    "review2" = c(NA, NA, NA, NA, "01/01/2002"), 
                    "death" = c("01/01/2002", "01/01/2002", NA, NA, NA))
print(data0)

# Microsoft Excel dates
data1 <- data.frame("id" = data0$id)
data1$diagnosis <- OR.date.Excel(data0$diagnosis)
data1$progression <- OR.date.Excel(data0$progression)
data1$review1 <- OR.date.Excel(data0$review1)
data1$review2 <- OR.date.Excel(data0$review2)
data1$death <- OR.date.Excel(data0$death)

# progression-free survival date is the date of progression or death, whichever is earlier
# last review date is the latest date patient was observed alive
data1$PFS <- OR.rowmin(cbind(data1$progression, data1$death)) 
data1$lastreview <- OR.rowmax(cbind(data1$review1, data1$review2))
print(data1)

# progression-free survival and overall survival
data2 <- data.frame("id" = data1$id)
data2$PFSmonths <- OR.survoutcome(data1$diagnosis, data1$PFS, data1$lastreview)[, 1]
data2$PFSstatus <- OR.survoutcome(data1$diagnosis, data1$PFS, data1$lastreview)[, 2]
data2$OSmonths <- OR.survoutcome(data1$diagnosis, data1$death, data1$lastreview)[, 1]
data2$OSstatus <- OR.survoutcome(data1$diagnosis, data1$death, data1$lastreview)[, 2]
print(data2)
```

### Example: outlier detection
```{r example_outlier}
y <- c(36.3, 47.9, 47.2, 43.9, 47.6, 49.6, 53.2, 59.3, 63.2, 70.8, 75.9, 88.5,
       97.3, 103.6, 6.1, 120.2, 135.8, 139.4)
x <- 1:length(y) - 1
fig1 <- OR.outliers.rlm.ggplot(x, y, max.degree = 4, p = 0.0027, x.title = "X",
                               y.breaks = seq(0, 150, 25), y.title = "Y")
print(fig1)
```
